//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNET_MVC_EF_EXAMPLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personels
    {
        public System.Guid PersonelID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public string PersonelName { get; set; }
        public string PersonelSirname { get; set; }
        public Nullable<int> PersonelAge { get; set; }
        public Nullable<double> PersonelSalary { get; set; }
        public Nullable<System.DateTime> PersonelBirthdate { get; set; }
        public Nullable<bool> PersonelGender { get; set; }
        public bool MarriageStatus { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
